#############################################################
# Author: Austin Sanders
# File: makefile
# Date: 2.15.18
# Description: This makes all my poorly written code into an exe
# Notes: none
#############################################################

SRC = main.cpp cell.cpp board.cpp game.cpp

HDR = board.hpp cell.hpp game.hpp

make:
	g++ $(SRC) $(HDR) -o run

clean:
	rm -f run
